version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: prometheus-grafana_grafana_1
      APP_PORT: 3000

  prometheus:
    image: prom/prometheus
    restart: on-failure
    user: "1000:1000"
    depends_on:
      - tasmota
    volumes:
      - ${APP_DATA_DIR}/data/prometheus/etc:/etc/prometheus/
      - ${APP_DATA_DIR}/data/prometheus/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    restart: on-failure
    user: "1000:1000"
    depends_on:
      - prometheus
    volumes:
      - ${APP_DATA_DIR}/data/grafana/etc:/etc/:rw
      - ${APP_DATA_DIR}/data/grafana/lib:/var/lib/:rw

  tasmota:
    image: ghcr.io/astr0n8t/tasmota-power-exporter:latest
    restart: always
    ports:
      - 9099:8000
    environment:
      - DEVICE_IP=192.168.178.85

  fritz-exporter:
    image: pdreker/fritz_exporter:2
    restart: always
    environment:
      FRITZ_HOSTNAME: 'fritz.box'
      FRITZ_USERNAME: 'prometheus'
      FRITZ_PASSWORD: 'prometheussecretlogin'
    ports:
      - "9787:9787"

#  mosquitto:
#    image: eclipse-mosquitto
#    volumes:
#      - ${APP_DATA_DIR}/data/mosquitto/conf:/mosquitto/config
#      - ${APP_DATA_DIR}/data/mosquitto/data:/mosquitto/data
#      - ${APP_DATA_DIR}/data/mosquitto/log:/mosquitto/log
#    ports:
#      - 8883:1883
#
#  tasmota-exporter:
#    image: eugenezadyra/tasmota-exporter:latest
#    environment:
#      MQTT_PORT: 8883
#      PROMETHEUS_EXPORTER_PORT: 9092
#    ports:
#      - '9092:9092'
#    restart: unless-stopped