version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: prometheus-grafana_grafana_1
      APP_PORT: 3000

  prometheus:
    image: prom/prometheus
    restart: on-failure
    user: "1000:1000"
    volumes:
      - ${APP_DATA_DIR}/data/prometheus/etc:/etc/prometheus/
      - ${APP_DATA_DIR}/data/prometheus/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    restart: on-failure
    user: "1000:1000"
    volumes:
      - ${APP_DATA_DIR}/data/grafana/etc:/etc/:rw
      - ${APP_DATA_DIR}/data/grafana/lib:/var/lib/:rw

  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - ${APP_DATA_DIR}/data/mosquitto/conf:/mosquitto/conf
      - ${APP_DATA_DIR}/data/mosquitto/data:/mosquitto/data
      - ${APP_DATA_DIR}/data/mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883

  tasmota-exporter:
    image: eugenezadyra/tasmota-exporter:latest
    environment:
      MQTT_HOSTNAME: umbrel.local
      MQTT_PORT: 1883
      PROMETHEUS_EXPORTER_PORT: 9092
    ports:
      - '9092:9092'
    restart: unless-stopped