version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: prometheus-grafana_grafana_1
      APP_PORT: 3000

  prometheus:
    image: prom/prometheus
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/prometheus:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"

  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana
    user: "1000:1000"
    volumes:
      - ${APP_DATA_DIR}/data/grafana/etc:/etc/:rw
      - ${APP_DATA_DIR}/data/grafana/lib:/var/lib/:rw