version: "3.7"

services:

  prometheus:
    image: prom/prometheus
    restart: on-failure
    user: "1000:1000"
    volumes:
      - ${APP_DATA_DIR}/data/prometheus/etc:/etc/prometheus/
      - ${APP_DATA_DIR}/data/prometheus/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"

  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana
    user: "1000:1000"
    volumes:
      - ${APP_DATA_DIR}/data/grafana/etc:/etc/:rw
      - ${APP_DATA_DIR}/data/grafana/lib:/var/lib/:rw
    ports:
      - "3000:3000"