manifestVersion: 1
id: prometheus-grafana
category: Development
name: prometheus-grafana
version: "0.1"
tagline: A Prometheus Grafana Stack
description: >-
  Description

releaseNotes: >-
  First Version
dependencies: []
developer: Martin Klewitz
website: https://klewitz.info
repo: https://github.com/martinklewitz
port: 3000
gallery:
  - https://raw.githubusercontent.com/prometheus/prometheus/main/documentation/images/prometheus-logo.svg
path: ""
defaultUsername: ""
defaultPassword: ""
submitter: martinklewitz
